// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "网课大赛";

const lessonData = [
    // ===== 第1段 =====
    ["学校", "xué xiào", "school", "sekolah"],
    ["举办", "jǔ bàn", "organise", "menganjurkan"],
    ["了", "le", "", ""],
    ["一场", "yī chǎng", "a", "satu"],
    ["“", "", "", ""],
    ["网课", "wǎng kè", "online class", "kelas dalam talian"],
    ["学习", "xué xí", "study", "belajar"],
    ["大赛", "dà sài", "competition", "pertandingan"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["各班", "gè bān", "each class", "setiap kelas"],
    ["推选", "tuī xuǎn", "nominate", "memilih"],
    ["一名", "yī míng", "one", "seorang"],
    ["代表", "dài biǎo", "representative", "wakil"],
    ["参加", "cān jiā", "participate", "menyertai"],
    ["。", "", "", ""],
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["和", "hé", "and", "dan"],
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["是", "shì", "are", "ialah"],
    ["同班同学", "tóng bān tóng xué", "classmates", "rakan sekelas"],
    ["，", "", "", ""],
    ["两人", "liǎng rén", "both", "kedua-dua"],
    ["都", "dōu", "both", "kedua-dua"],
    ["报名", "bào míng", "signed up", "mendaftar"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["平时", "píng shí", "usually", "biasanya"],
    ["上网课", "shàng wǎng kè", "attend online class", "menghadiri kelas dalam talian"],
    ["态度", "tài dù", "attitude", "sikap"],
    ["散漫", "sǎn màn", "slack", "lalai"],
    ["，", "", "", ""],
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["则", "zé", "then", "manakala"],
    ["自律", "zì lǜ", "self-disciplined", "berdisiplin"],
    ["认真", "rèn zhēn", "serious", "serius"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["比赛", "bǐ sài", "competition", "pertandingan"],
    ["前一天", "qián yī tiān", "the day before", "sehari sebelum"],
    ["，", "", "", ""],
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["唉声叹气", "āi shēng tàn qì", "sighing and groaning", "mengeluh"],
    ["地", "de", "", ""],
    ["对", "duì", "to", "kepada"],
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["明天", "míng tiān", "tomorrow", "esok"],
    ["就", "jiù", "will", "akan"],
    ["要", "yào", "have to", "perlu"],
    ["比赛", "bǐ sài", "compete", "bertanding"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["食不下咽", "shí bù xià yàn", "cannot eat", "tidak lalu makan"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["笑着", "xiào zhe", "laughing", "sambil ketawa"],
    ["回答", "huí dá", "answered", "menjawab"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["可", "kě", "but", "tetapi"],
    ["你", "nǐ", "you", "awak"],
    ["刚才", "gāng cái", "just now", "tadi"],
    ["不是", "bù shì", "didn't", "bukankah"],
    ["还", "hái", "still", "masih"],
    ["吃了", "chī le", "ate", "makan"],
    ["三大碗", "sān dà wǎn", "three big bowls", "tiga mangkuk besar"],
    ["饭", "fàn", "rice", "nasi"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["又", "yòu", "again", "lagi"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["昨晚", "zuó wǎn", "last night", "malam tadi"],
    ["还", "hái", "also", "juga"],
    ["彻夜难眠", "chè yè nán mián", "sleepless all night", "tidak dapat tidur sepanjang malam"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["打趣", "dǎ qù", "teased", "bergurau"],
    ["道", "dào", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["难怪", "nán guài", "no wonder", "tidak hairanlah"],
    ["你", "nǐ", "you", "awak"],
    ["今天", "jīn tiān", "today", "hari ini"],
    ["日上三竿", "rì shàng sān gān", "late in the morning", "matahari sudah tinggi"],
    ["才", "cái", "only then", "barulah"],
    ["起床", "qǐ chuáng", "wake up", "bangun tidur"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["心虚", "xīn xū", "guilty", "rasa bersalah"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["哎呀", "āi yā", "oh", "alamak"],
    ["，", "", "", ""],
    ["不管", "bù guǎn", "no matter", "tidak kira"],
    ["什么", "shén me", "what", "apa"],
    ["都", "dōu", "all", "semua"],
    ["瞒不过", "mán bù guò", "cannot hide from", "tidak dapat sembunyi"],
    ["你", "nǐ", "you", "awak"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["认真", "rèn zhēn", "seriously", "serius"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["看", "kàn", "see", "lihat"],
    ["你", "nǐ", "your", "awak"],
    ["平时", "píng shí", "usually", "biasanya"],
    ["上网课", "shàng wǎng kè", "attend online class", "menghadiri kelas dalam talian"],
    ["的", "de", "", ""],
    ["态度", "tài dù", "attitude", "sikap"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["知道", "zhī dào", "know", "tahu"],
    ["你", "nǐ", "you", "awak"],
    ["这次", "zhè cì", "this time", "kali ini"],
    ["比赛", "bǐ sài", "competition", "pertandingan"],
    ["凶多吉少", "xiōng duō jí shǎo", "more danger than safety", "banyak bahaya sedikit selamat"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["不服气", "bù fú qì", "not convinced", "tidak puas hati"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["别", "bié", "don't", "jangan"],
    ["胡说八道", "hú shuō bā dào", "talk nonsense", "cakap bukan-bukan"],
    ["！", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["可是", "kě shì", "is", "adalah"],
    ["有", "yǒu", "have", "ada"],
    ["孙悟空", "sūn wù kōng", "Sun Wukong", "Sun Wukong"],
    ["的", "de", "", ""],
    ["‘", "", "", ""],
    ["火眼金睛", "huǒ yǎn jīn jīng", "fiery golden eyes", "mata emas berapi"],
    ["’", "", "", ""],
    ["，", "", "", ""],
    ["任何", "rèn hé", "any", "mana-mana"],
    ["事", "shì", "thing", "perkara"],
    ["都", "dōu", "all", "semua"],
    ["逃不过", "táo bù guò", "cannot escape", "tidak dapat lari"],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["法眼", "fǎ yǎn", "discerning eye", "mata yang tajam"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["笑着", "xiào zhe", "laughing", "sambil ketawa"],
    ["反击", "fǎn jī", "countered", "membalas"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["才", "cái", "just", "baru"],
    ["不是", "bù shì", "is not", "bukan"],
    ["孙悟空", "sūn wù kōng", "Sun Wukong", "Sun Wukong"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["是", "shì", "are", "ialah"],
    ["‘", "", "", ""],
    ["披着人皮", "pī zhe rén pí", "wearing human skin", "berkulit manusia"],
    ["的", "de", "", ""],
    ["虫", "chóng", "worm", "ulat"],
    ["’", "", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["追问", "zhuī wèn", "asked further", "bertanya lagi"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["虫", "chóng", "worm", "ulat"],
    ["？", "", "", ""],
    ["什么", "shén me", "what", "apa"],
    ["虫", "chóng", "worm", "ulat"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    // ===== 第11段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["答道", "dá dào", "answered", "menjawab"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["懒惰虫", "lǎn duò chóng", "lazy worm", "ulat pemalas"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    // ===== 第12段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["脸", "liǎn", "face", "muka"],
    ["一红", "yī hóng", "turned red", "menjadi merah"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["……", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["……", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["是", "shì", "is", "ialah"],
    ["在", "zài", "in", "sedang"],
    ["侮辱", "wǔ rǔ", "insult", "menghina"],
    ["你", "nǐ", "your", "awak"],
    ["的", "de", "", ""],
    ["同班同学", "tóng bān tóng xué", "classmate", "rakan sekelas"],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    // ===== 第13段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["（", "", "", ""],
    ["小声", "xiǎo shēng", "softly", "perlahan"],
    ["）", "", "", ""],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["平时", "píng shí", "usually", "biasanya"],
    ["反应迟钝", "fǎn yìng chí dùn", "slow response", "lambat bertindak"],
    ["，", "", "", ""],
    ["今天", "jīn tiān", "today", "hari ini"],
    ["脑筋", "nǎo jīn", "brain", "otak"],
    ["怎么", "zěn me", "how", "bagaimana"],
    ["转", "zhuàn", "turn", "berputar"],
    ["得", "de", "", ""],
    ["那么", "nà me", "so", "begitu"],
    ["快", "kuài", "fast", "cepat"],
    ["？", "", "", ""],
    ["太阳", "tài yáng", "sun", "matahari"],
    ["打", "dǎ", "from", "dari"],
    ["西边", "xī biān", "west", "barat"],
    ["出来", "chū lái", "come out", "keluar"],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["（", "", "", ""],
    ["赶紧", "gǎn jǐn", "hurriedly", "segera"],
    ["往", "wǎng", "towards", "ke"],
    ["外面", "wài miàn", "outside", "luar"],
    ["看", "kàn", "look", "lihat"],
    ["）", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    // ===== 第14段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["（", "", "", ""],
    ["大声", "dà shēng", "loudly", "kuat"],
    ["）", "", "", ""],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["说", "shuō", "say", "berkata"],
    ["什么", "shén me", "what", "apa"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第15段

    // ===== 第15段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["连忙", "lián máng", "hurriedly", "segera"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["没什么", "méi shén me", "nothing", "tiada apa-apa"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["说", "shuō", "said", "berkata"],
    ["你", "nǐ", "you", "awak"],
    ["是", "shì", "are", "ialah"],
    ["个", "gè", "", ""],
    ["活泼可爱", "huó pō kě ài", "lively and cute", "ceria dan comel"],
    ["、", "", "", ""],
    ["彬彬有礼", "bīn bīn yǒu lǐ", "polite", "sopan santun"],
    ["、", "", "", ""],
    ["人见人爱", "rén jiàn rén ài", "loved by all", "disukai semua"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "child", "kanak-kanak"],
    ["啊", "a", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第16段

    // ===== 第16段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["哼", "hēng", "hmph", "hmph"],
    ["了", "le", "", ""],
    ["一声", "yī shēng", "one sound", "satu bunyi"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["算", "suàn", "consider", "kira"],
    ["你", "nǐ", "you", "awak"],
    ["识相", "shí xiàng", "sensible", "tahu diri"],
    ["，", "", "", ""],
    ["要不", "yào bù", "otherwise", "kalau tidak"],
    ["我", "wǒ", "I", "saya"],
    ["就", "jiù", "then", "lalu"],
    ["向", "xiàng", "to", "kepada"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["告状", "gào zhuàng", "complain", "mengadu"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第17段

    // ===== 第17段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["是是是", "shì shì shì", "yes yes yes", "ya ya ya"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["最", "zuì", "most", "paling"],
    ["爱", "ài", "love to", "suka"],
    ["仗着", "zhàng zhe", "relying on", "bergantung pada"],
    ["是", "shì", "is", "ialah"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["的", "de", "", ""],
    ["心肝宝贝儿", "xīn gān bǎo bèi ér", "darling", "buah hati"],
    ["就", "jiù", "then", "lalu"],
    ["作成作福", "zuò wēi zuò fú", "abuse power", "menyalahgunakan kuasa"],
    ["。", "", "", ""],
    ["就快", "jiù kuài", "soon", "hampir"],
    ["比赛", "bǐ sài", "compete", "bertanding"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["快", "kuài", "quickly", "cepat"],
    ["准备", "zhǔn bèi", "prepare", "bersedia"],
    ["吧", "ba", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第18段

    // ===== 第18段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["摆摆手", "bǎi bǎi shǒu", "waved hand", "melambai tangan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["哎呀", "āi yā", "oh", "alamak"],
    ["，", "", "", ""],
    ["瞧", "qiáo", "look", "lihat"],
    ["你", "nǐ", "you", "awak"],
    ["紧张", "jǐn zhāng", "nervous", "gelisah"],
    ["的", "de", "", ""],
    ["模样", "mú yàng", "appearance", "rupa"],
    ["，", "", "", ""],
    ["只要", "zhǐ yào", "as long as", "asalkan"],
    ["我", "wǒ", "I", "saya"],
    ["不", "bù", "not", "tidak"],
    ["开启", "kāi qǐ", "turn on", "hidupkan"],
    ["摄像头", "shè xiàng tóu", "camera", "kamera"],
    ["，", "", "", ""],
    ["评委", "píng wěi", "judges", "juri"],
    ["也", "yě", "also", "juga"],
    ["不知道", "bù zhī dào", "don't know", "tidak tahu"],
    ["我", "wǒ", "I", "saya"],
    ["在", "zài", "is", "sedang"],
    ["干", "gàn", "do", "buat"],
    ["什么", "shén me", "what", "apa"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第19段

    // ===== 第19段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["不慌不忙", "bù huāng bù máng", "unhurriedly", "tanpa tergesa-gesa"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["不瞒", "bù mán", "to be honest", "sejujurnya"],
    ["你", "nǐ", "you", "awak"],
    ["说", "shuō", "say", "berkata"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["可是", "kě shì", "is", "adalah"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["派来", "pài lái", "sent", "dihantar"],
    ["的", "de", "", ""],
    ["间谍", "jiàn dié", "spy", "perisik"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第20段

    // ===== 第20段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["愣", "lèng", "stunned", "terkejut"],
    ["了", "le", "", ""],
    ["一下", "yī xià", "for a moment", "seketika"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["咦", "yí", "huh", "eh"],
    ["，", "", "", ""],
    ["间谍", "jiàn dié", "spy", "perisik"],
    ["是", "shì", "is", "ialah"],
    ["什么", "shén me", "what", "apa"],
    ["？", "", "", ""],
    ["可以", "kě yǐ", "can", "boleh"],
    ["吃", "chī", "eat", "makan"],
    ["的", "de", "", ""],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第21段

    // ===== 第21段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["叹气", "tàn qì", "sighed", "mengeluh"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["吃", "chī", "eat", "makan"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["就", "jiù", "only", "hanya"],
    ["只", "zhǐ", "only", "hanya"],
    ["想到", "xiǎng dào", "think of", "fikir"],
    ["吃", "chī", "eat", "makan"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第22段

    // ===== 第22段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["理直气壮", "lǐ zhí qì zhuàng", "confidently", "dengan yakin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["当然", "dāng rán", "of course", "tentulah"],
    ["，", "", "", ""],
    ["民以食为天", "mín yǐ shí wéi tiān", "food is heaven for the people", "makanan adalah syurga rakyat"],
    ["嘛", "ma", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第23段

    // ===== 第23段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["严肃", "yán sù", "seriously", "serius"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["平时", "píng shí", "usually", "biasanya"],
    ["边", "biān", "while", "sambil"],
    ["吃", "chī", "eat", "makan"],
    ["零食", "líng shí", "snacks", "snek"],
    ["边", "biān", "while", "sambil"],
    ["听课", "tīng kè", "listen to class", "dengar kelas"],
    ["，", "", "", ""],
    ["甚至", "shèn zhì", "even", "malah"],
    ["打瞌睡", "dǎ kē shuì", "doze off", "mengantuk"],
    ["的", "de", "", ""],
    ["画面", "huà miàn", "scene", "gambar"],
    ["全都", "quán dōu", "all", "semua"],
    ["被", "bèi", "by", "oleh"],
    ["我", "wǒ", "me", "saya"],
    ["拍下来", "pāi xià lái", "captured", "tangkap"],
    ["了", "le", "", ""],
    ["！", "", "", ""],
    ["还有", "hái yǒu", "there is also", "masih ada"],
    ["一张", "yī zhāng", "a", "satu"],
    ["……", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第24段

    // ===== 第24段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["紧张", "jǐn zhāng", "nervous", "gelisah"],
    ["地", "de", "", ""],
    ["问", "wèn", "asked", "bertanya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["什么", "shén me", "what", "apa"],
    ["？", "", "", ""],
    ["哪一张", "nǎ yī zhāng", "which one", "yang mana satu"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第25段

    // ===== 第25段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["就是", "jiù shì", "is", "iaitu"],
    ["你", "nǐ", "you", "awak"],
    ["赤裸", "chì luǒ", "naked", "bogel"],
    ["着", "zhe", "", ""],
    ["上身", "shàng shēn", "upper body", "badan atas"],
    ["听课", "tīng kè", "listen to class", "dengar kelas"],
    ["的", "de", "", ""],
    ["那", "nà", "that", "itu"],
    ["一张", "yī zhāng", "one", "satu"],
    ["照片", "zhào piàn", "photo", "gambar"],
    ["！", "", "", ""],
    ["只差", "zhǐ chà", "only short of", "hanya kurang"],
    ["这张", "zhè zhāng", "this", "ini"],
    ["评委", "píng wěi", "judges", "juri"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["没", "méi", "not", "tidak"],
    ["看过", "kàn guò", "seen", "pernah melihat"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第26段

    // ===== 第26段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["急得", "jí de", "anxiously", "dengan cemas"],
    ["直", "zhí", "continuously", "terus"],
    ["跺脚", "duò jiǎo", "stomp feet", "menghentak kaki"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["……", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["……", "", "", ""],
    ["这个", "zhè gè", "this", "ini"],
    ["胳膊肘儿朝外拐", "gē bo zhǒu ér cháo wài guǎi", "betray one's own", "berpihak kepada orang luar"],
    ["的", "de", "", ""],
    ["坏同学", "huài tóng xué", "bad classmate", "rakan sekelas jahat"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["（", "", "", ""],
    ["作势", "zuò shì", "pretend", "berpura-pura"],
    ["要哭", "yào kū", "about to cry", "mahu menangis"],
    ["）", "", "", ""],

    ["\n", "", "", ""], // 👈 第27段

    // ===== 第27段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["劝道", "quàn dào", "advised", "menasihati"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["哭", "kū", "cry", "menangis"],
    ["也", "yě", "also", "juga"],
    ["没用", "méi yòng", "useless", "tidak berguna"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["倒不如", "dào bù rú", "might as well", "lebih baik"],
    ["乖乖", "guāi guāi", "obediently", "dengan patuh"],
    ["遵守", "zūn shǒu", "obey", "mematuhi"],
    ["比赛", "bǐ sài", "competition", "pertandingan"],
    ["的", "de", "", ""],
    ["规则", "guī zé", "rules", "peraturan"],
    ["……", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第28段

    // ===== 第28段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["（", "", "", ""],
    ["立马", "lì mǎ", "immediately", "segera"],
    ["打断", "dǎ duàn", "interrupt", "memotong"],
    ["）", "", "", ""],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["知道", "zhī dào", "know", "tahu"],
    ["！", "", "", ""],
    ["要", "yào", "must", "perlu"],
    ["专心", "zhuān xīn", "attentively", "tumpuan"],
    ["上课", "shàng kè", "attend class", "menghadiri kelas"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第29段

    // ===== 第29段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["点头", "diǎn tóu", "nodded", "mengangguk"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["说对", "shuō duì", "said correctly", "betul cakap"],
    ["了", "le", "", ""],
    ["！", "", "", ""],
    ["还要", "hái yào", "also must", "juga perlu"],
    ["衣着整齐", "yī zhuó zhěng qí", "dressed neatly", "berpakaian rapi"],
    ["、", "", "", ""],
    ["坐姿端正", "zuò zī duān zhèng", "sit upright", "duduk tegak"],
    ["，", "", "", ""],
    ["还有", "hái yǒu", "and also", "dan juga"],
    ["……", "", "", ""],
    ["”", "", "", ""],
    ["（", "", "", ""],
    ["双手叉腰", "shuāng shǒu chā yāo", "hands on hips", "tangan di pinggang"],
    ["）", "", "", ""],

    ["\n", "", "", ""], // 👈 第30段

    // ===== 第30段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["连忙", "lián máng", "hurriedly", "segera"],
    ["喊停", "hǎn tíng", "shouted stop", "jerit berhenti"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["停停停", "tíng tíng tíng", "stop stop stop", "berhenti berhenti"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["怎么", "zěn me", "how", "bagaimana"],
    ["比", "bǐ", "than", "daripada"],
    ["八十岁", "bā shí suì", "eighty years old", "lapan puluh tahun"],
    ["的", "de", "", ""],
    ["老太婆", "lǎo tài pó", "old woman", "nenek tua"],
    ["还", "hái", "still", "masih"],
    ["唠叨", "láo dao", "nagging", "berleter"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第31段

    // ===== 第31段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["反驳", "fǎn bó", "retorted", "membalas"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["哼", "hēng", "hmph", "hmph"],
    ["！", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["唠叨", "láo dao", "nagging", "berleter"],
    ["都", "dōu", "also", "juga"],
    ["比", "bǐ", "than", "daripada"],
    ["你", "nǐ", "you", "awak"],
    ["说谎", "shuō huǎng", "lie", "berbohong"],
    ["不", "bù", "not", "tidak"],
    ["打草稿", "dǎ cǎo gǎo", "draft", "draf"],
    ["来", "lái", "come", "datang"],
    ["得", "de", "", ""],
    ["好", "hǎo", "good", "baik"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第32段

    // ===== 第32段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["辩解", "biàn jiě", "defended", "mempertahankan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["从不说谎", "cóng bù shuō huǎng", "never lie", "tidak pernah berbohong"],
    ["，", "", "", ""],
    ["更", "gèng", "moreover", "lagi"],
    ["何况", "hé kuàng", "let alone", "lagipun"],
    ["说", "shuō", "say", "berkata"],
    ["要", "yào", "must", "perlu"],
    ["比", "bǐ", "than", "daripada"],
    ["写", "xiě", "write", "tulis"],
    ["快", "kuài", "fast", "cepat"],
    ["嘛", "ma", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第33段

    // ===== 第33段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["反问", "fǎn wèn", "asked in reply", "bertanya balik"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["是", "shì", "is", "ialah"],
    ["谁", "shuí", "who", "siapa"],
    ["每次", "měi cì", "every time", "setiap kali"],
    ["在", "zài", "when", "apabila"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["指名", "zhǐ míng", "name", "menamakan"],
    ["回答", "huí dá", "answer", "menjawab"],
    ["问题", "wèn tí", "question", "soalan"],
    ["时", "shí", "when", "apabila"],
    ["故意", "gù yì", "deliberately", "sengaja"],
    ["下线", "xià xiàn", "go offline", "log keluar"],
    ["，", "", "", ""],
    ["把", "bǎ", "", ""],
    ["罪", "zuì", "blame", "salah"],
    ["怪到", "guài dào", "blame on", "salahkan"],
    ["网络", "wǎng luò", "network", "rangkaian"],
    ["头上", "tóu shàng", "head", "kepala"],
    ["去", "qù", "to", "ke"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第34段

    // ===== 第34段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["（", "", "", ""],
    ["心虚", "xīn xū", "guilty", "rasa bersalah"],
    ["）", "", "", ""],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["嘘", "xū", "shh", "syh"],
    ["！", "", "", ""],
    ["为什么", "wèi shén me", "why", "kenapa"],
    ["你", "nǐ", "you", "awak"],
    ["连", "lián", "even", "sehingga"],
    ["这", "zhè", "this", "ini"],
    ["件", "jiàn", "matter", "perkara"],
    ["事", "shì", "matter", "perkara"],
    ["也", "yě", "also", "juga"],
    ["知道", "zhī dào", "know", "tahu"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第35段

    // ===== 第35段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["（", "", "", ""],
    ["拉着", "lā zhe", "pulling", "menarik"],
    ["两条", "liǎng tiáo", "two", "dua"],
    ["小辫儿", "xiǎo biàn ér", "small braids", "tocang kecil"],
    ["，", "", "", ""],
    ["一脸", "yī liǎn", "a face of", "muka"],
    ["神气", "shén qì", "proud", "bangga"],
    ["）", "", "", ""],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["要", "yào", "must", "perlu"],
    ["怪", "guài", "blame", "salahkan"],
    ["你", "nǐ", "you", "awak"],
    ["总是", "zǒng shì", "always", "sentiasa"],
    ["沉醉", "chén zuì", "immersed", "tenggelam"],
    ["在", "zài", "in", "di"],
    ["自己", "zì jǐ", "own", "sendiri"],
    ["的", "de", "", ""],
    ["世界", "shì jiè", "world", "dunia"],
    ["里", "lǐ", "in", "dalam"],
    ["，", "", "", ""],
    ["当", "dāng", "treat", "anggap"],
    ["我", "wǒ", "me", "saya"],
    ["是", "shì", "is", "ialah"],
    ["透明", "tòu míng", "transparent", "lutsinar"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第36段

    // ===== 第36段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["感慨", "gǎn kǎi", "sighed with emotion", "berasa hiba"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["哎", "āi", "sigh", "alah"],
    ["，", "", "", ""],
    ["别人", "bié rén", "others", "orang lain"],
    ["都是", "dōu shì", "are all", "semuanya"],
    ["同学", "tóng xué", "classmates", "rakan sekelas"],
    ["相亲相爱", "xiāng qīn xiāng ài", "love each other", "saling menyayangi"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["我们", "wǒ men", "we", "kita"],
    ["却", "què", "yet", "namun"],
    ["总是", "zǒng shì", "always", "sentiasa"],
    ["互相伤害", "hù xiāng shāng hài", "hurt each other", "saling melukai"],
    ["。", "", "", ""],
    ["莫非", "mò fēi", "could it be", "adakah"],
    ["你", "nǐ", "you", "awak"],
    ["这辈子", "zhè bèi zi", "this life", "seumur hidup ini"],
    ["是", "shì", "are", "ialah"],
    ["来", "lái", "come", "datang"],
    ["讨债", "tǎo zhài", "collect debt", "menuntut hutang"],
    ["的", "de", "", ""],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第37段

    // ===== 第37段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["提醒", "tí xǐng", "reminded", "mengingatkan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["可别", "kě bié", "don't", "jangan"],
    ["这么说", "zhè me shuō", "say so", "berkata begitu"],
    ["，", "", "", ""],
    ["难道", "nán dào", "could it be", "adakah"],
    ["你", "nǐ", "you", "awak"],
    ["忘了", "wàng le", "forgot", "lupa"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["常说的", "cháng shuō de", "often said", "selalu berkata"],
    ["话", "huà", "words", "kata-kata"],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第38段

    // ===== 第38段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["回答", "huí dá", "answered", "menjawab"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["当然", "dāng rán", "of course", "tentulah"],
    ["记得", "jì de", "remember", "ingat"],
    ["——", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["都是", "dōu shì", "are all", "semuanya"],
    ["为", "wèi", "for", "untuk"],
    ["你", "nǐ", "you", "awak"],
    ["好", "hǎo", "good", "baik"],
    ["嘛", "ma", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第39段

    // ===== 第39段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["笑道", "xiào dào", "laughed and said", "ketawa dan berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["对啊", "duì a", "right", "betul"],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "so", "jadi"],
    ["我", "wǒ", "I", "saya"],
    ["这", "zhè", "this", "ini"],
    ["是", "shì", "is", "ialah"],
    ["用心良苦", "yòng xīn liáng kǔ", "well-intentioned", "berniat baik"],
    ["啊", "a", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第40段

    // ===== 第40段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["（", "", "", ""],
    ["带着", "dài zhe", "with", "dengan"],
    ["讽刺", "fěng cì", "sarcasm", "sindiran"],
    ["的", "de", "", ""],
    ["语气", "yǔ qì", "tone", "nada"],
    ["）", "", "", ""],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["看来", "kàn lái", "it seems", "nampaknya"],
    ["是", "shì", "is", "ialah"],
    ["我", "wǒ", "I", "saya"],
    ["误会", "wù huì", "misunderstood", "salah faham"],
    ["你", "nǐ", "you", "awak"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["真是", "zhēn shì", "really", "benar-benar"],
    ["身在福中不知福", "shēn zài fú zhōng bù zhī fú", "not knowing one's blessings", "tidak tahu bersyukur"],
    ["啊", "a", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第41段

    // ===== 第41段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["大方", "dà fāng", "generously", "dengan murah hati"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["看在", "kàn zài", "for the sake of", "demi"],
    ["咱俩", "zán liǎ", "we two", "kita berdua"],
    ["同学", "tóng xué", "classmates", "rakan sekelas"],
    ["一场", "yī chǎng", "a", "satu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["就", "jiù", "then", "lalu"],
    ["传授", "chuán shòu", "teach", "mengajar"],
    ["独门招式", "dú mén zhāo shì", "secret technique", "teknik rahsia"],
    ["——", "", "", ""],
    ["‘", "", "", ""],
    ["网课三部曲", "wǎng kè sān bù qǔ", "three steps of online class", "tiga langkah kelas dalam talian"],
    ["’", "", "", ""],
    ["给", "gěi", "to", "kepada"],
    ["你", "nǐ", "you", "awak"],
    ["吧", "ba", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第42段

    // ===== 第42段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["眼睛", "yǎn jīng", "eyes", "mata"],
    ["一亮", "yī liàng", "lit up", "menyala"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["哪三部", "nǎ sān bù", "which three", "yang mana tiga"],
    ["？", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["洗耳恭听", "xǐ ěr gōng tīng", "listen attentively", "mendengar dengan teliti"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第43段

    // ===== 第43段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["耐心", "nài xīn", "patiently", "dengan sabar"],
    ["解释", "jiě shì", "explained", "menjelaskan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["第一部", "dì yī bù", "first step", "langkah pertama"],
    ["——", "", "", ""],
    ["课前", "kè qián", "before class", "sebelum kelas"],
    ["预习", "yù xí", "preview", "ulang kaji awal"],
    ["课文", "kè wén", "text", "teks"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第44段

    // ===== 第44段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["得意", "dé yì", "proudly", "dengan bangga"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["简单", "jiǎn dān", "simple", "mudah"],
    ["！", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["能够", "néng gòu", "can", "boleh"],
    ["一目十行", "yī mù shí háng", "read ten lines at a glance", "baca sepuluh baris sekali pandang"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第45段

    // ===== 第45段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["深深", "shēn shēn", "deeply", "dalam"],
    ["吸", "xī", "inhale", "sedut"],
    ["一口气", "yī kǒu qì", "a breath", "satu nafas"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["！", "", "", ""],
    ["第二部", "dì èr bù", "second step", "langkah kedua"],
    ["——", "", "", ""],
    ["上课时", "shàng kè shí", "during class", "semasa kelas"],
    ["要", "yào", "must", "perlu"],
    ["有", "yǒu", "have", "ada"],
    ["四到", "sì dào", "four arrivings", "empat sampai"],
    ["：", "", "", ""],
    ["眼到", "yǎn dào", "eyes on", "mata sampai"],
    ["、", "", "", ""],
    ["心到", "xīn dào", "heart on", "hati sampai"],
    ["、", "", "", ""],
    ["手到", "shǒu dào", "hands on", "tangan sampai"],
    ["，", "", "", ""],
    ["还有", "hái yǒu", "and also", "dan juga"],
    ["……", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第46段

    // ===== 第46段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["抢答", "qiǎng dá", "answered first", "menjawab dahulu"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["知道", "zhī dào", "know", "tahu"],
    ["！", "", "", ""],
    ["迟到", "chí dào", "late", "lewat"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第47段

    // ===== 第47段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["生气", "shēng qì", "angry", "marah"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["别", "bié", "don't", "jangan"],
    ["胡说八道", "hú shuō bā dào", "talk nonsense", "cakap bukan-bukan"],
    ["！", "", "", ""],
    ["还有", "hái yǒu", "and also", "dan juga"],
    ["一个", "yī gè", "one", "satu"],
    ["是", "shì", "is", "ialah"],
    ["口到", "kǒu dào", "mouth on", "mulut sampai"],
    ["！", "", "", ""],
    ["遇到", "yù dào", "encounter", "menghadapi"],
    ["问题", "wèn tí", "problem", "masalah"],
    ["就", "jiù", "then", "lalu"],
    ["要", "yào", "must", "perlu"],
    ["发问", "fā wèn", "ask", "bertanya"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第48段

    // ===== 第48段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["反驳", "fǎn bó", "retorted", "membalas"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["有", "yǒu", "have", "ada"],
    ["啊", "a", "", ""],
    ["！", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["每次", "měi cì", "every time", "setiap kali"],
    ["都是", "dōu shì", "am always", "sentiasa"],
    ["第一个", "dì yī gè", "first", "pertama"],
    ["问", "wèn", "ask", "tanya"],
    ["老师", "lǎo shī", "teacher", "guru"],
    ["几点", "jǐ diǎn", "what time", "pukul berapa"],
    ["下课", "xià kè", "class ends", "tamat kelas"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第49段

    // ===== 第49段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["忽视", "hū shì", "ignored", "mengabaikan"],
    ["他", "tā", "him", "dia"],
    ["，", "", "", ""],
    ["继续", "jì xù", "continued", "meneruskan"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["第三部", "dì sān bù", "third step", "langkah ketiga"],
    ["——", "", "", ""],
    ["课后", "kè hòu", "after class", "selepas kelas"],
    ["准时", "zhǔn shí", "on time", "tepat masa"],
    ["完成", "wán chéng", "complete", "menyiapkan"],
    ["功课", "gōng kè", "homework", "kerja sekolah"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第50段

    // ===== 第50段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["摆摆手", "bǎi bǎi shǒu", "waved hand", "melambai tangan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["哎呀", "āi yā", "oh", "alamak"],
    ["，", "", "", ""],
    ["不", "bù", "not", "tidak"],
    ["做", "zuò", "do", "buat"],
    ["功课", "gōng kè", "homework", "kerja sekolah"],
    ["也", "yě", "also", "juga"],
    ["无所谓", "wú suǒ wèi", "doesn't matter", "tidak mengapa"],
    ["，", "", "", ""],
    ["反正", "fǎn zhèng", "anyway", "lagipun"],
    ["网课", "wǎng kè", "online class", "kelas dalam talian"],
    ["效率", "xiào lǜ", "efficiency", "kecekapan"],
    ["低", "dī", "low", "rendah"],
    ["嘛", "ma", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第51段

    // ===== 第51段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["严肃", "yán sù", "seriously", "serius"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["是", "shì", "is", "ialah"],
    ["你", "nǐ", "you", "awak"],
    ["这个", "zhè gè", "this", "ini"],
    ["懒惰虫", "lǎn duò chóng", "lazy worm", "ulat pemalas"],
    ["的", "de", "", ""],
    ["借口", "jiè kǒu", "excuse", "alasan"],
    ["，", "", "", ""],
    ["像", "xiàng", "like", "seperti"],
    ["你", "nǐ", "you", "awak"],
    ["那么", "nà me", "so", "begitu"],
    ["不自律", "bù zì lǜ", "undisciplined", "tidak berdisiplin"],
    ["，", "", "", ""],
    ["就算", "jiù suàn", "even if", "walaupun"],
    ["是", "shì", "is", "ialah"],
    ["神仙", "shén xiān", "immortal", "dewa"],
    ["也", "yě", "also", "juga"],
    ["救不了", "jiù bù liǎo", "cannot save", "tidak dapat selamatkan"],
    ["你", "nǐ", "you", "awak"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第52段

    // ===== 第52段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["笑道", "xiào dào", "laughed", "ketawa"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["神仙", "shén xiān", "immortal", "dewa"],
    ["？", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["知道", "zhī dào", "know", "tahu"],
    ["！", "", "", ""],
    ["八仙过海", "bā xiān guò hǎi", "Eight Immortals cross the sea", "Lapan Dewa menyeberangi laut"],
    ["，", "", "", ""],
    ["各显神通", "gè xiǎn shén tōng", "each shows their power", "masing-masing menunjukkan kehebatan"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第53段

    // ===== 第53段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["叹气", "tàn qì", "sighed", "mengeluh"],
    ["道", "dào", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["唉", "āi", "sigh", "alah"],
    ["，", "", "", ""],
    ["真是", "zhēn shì", "really", "benar-benar"],
    ["孺子不可教也", "rú zǐ bù kě jiào yě", "uneducable child", "anak yang tidak dapat diajar"],
    ["！", "", "", ""],
    ["算了", "suàn le", "forget it", "lupakanlah"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["还是", "hái shì", "better", "lebih baik"],
    ["不要", "bù yào", "don't", "jangan"],
    ["耽误", "dān wù", "delay", "melambatkan"],
    ["彼此", "bǐ cǐ", "each other", "satu sama lain"],
    ["的", "de", "", ""],
    ["比赛", "bǐ sài", "competition", "pertandingan"],
    ["准备", "zhǔn bèi", "preparation", "persiapan"],
    ["时间", "shí jiān", "time", "masa"],
    ["吧", "ba", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第54段

    // ===== 第54段 =====
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["却", "què", "but", "tetapi"],
    ["充满", "chōng mǎn", "full of", "penuh"],
    ["信心", "xìn xīn", "confidence", "keyakinan"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["放心", "fàng xīn", "rest assured", "yakinlah"],
    ["吧", "ba", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "have", "ada"],
    ["你", "nǐ", "you", "awak"],
    ["这", "zhè", "this", "ini"],
    ["位", "wèi", "", ""],
    ["天底下", "tiān dǐ xià", "under heaven", "di bawah langit"],
    ["最好", "zuì hǎo", "best", "terbaik"],
    ["的", "de", "", ""],
    ["同学", "tóng xué", "classmate", "rakan sekelas"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["这个", "zhè gè", "this", "ini"],
    ["懒惰虫", "lǎn duò chóng", "lazy worm", "ulat pemalas"],
    ["总有一天", "zǒng yǒu yī tiān", "one day", "satu hari nanti"],
    ["也", "yě", "also", "juga"],
    ["会", "huì", "will", "akan"],
    ["蜕变", "tuì biàn", "transform", "berubah"],
    ["成", "chéng", "into", "menjadi"],
    ["蝴蝶", "hú dié", "butterfly", "rama-rama"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["（", "", "", ""],
    ["敬礼", "jìng lǐ", "salute", "tabik"],
    ["）", "", "", ""],

    ["\n", "", "", ""], // 👈 第55段

    // ===== 第55段 =====
    ["小华", "xiǎo huá", "Xiao Hua", "Xiao Hua"],
    ["、", "", "", ""],
    ["小明", "xiǎo míng", "Xiao Ming", "Xiao Ming"],
    ["：", "", "", ""],
    ["（", "", "", ""],
    ["鞠躬", "jū gōng", "bow", "tunduk"],
    ["）", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
